export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  AI_INVALID_OUTPUT: 'AI_INVALID_OUTPUT',
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  EXTERNAL_DATA_ERROR: 'EXTERNAL_DATA_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS: Readonly<Record<ErrorCode, number>> = {
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.AUTH_REQUIRED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.PRODUCT_NOT_FOUND]: 404,
  [ERROR_CODES.OUT_OF_STOCK]: 409,
  [ERROR_CODES.AI_INVALID_OUTPUT]: 502,
  [ERROR_CODES.AI_PROVIDER_TIMEOUT]: 504,
  [ERROR_CODES.AI_RATE_LIMITED]: 429,
  [ERROR_CODES.EXTERNAL_DATA_ERROR]: 502,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
};
